### ISSUE TITLE
Mark Synonyms & Hybrids in Taxon Spine

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#28]
The Taxonomic Spine should be expanded with Synonyms & Hybrids and these should be marked as such for import into Specify. 

Synonyms :
- [ ] Add column "Accepted" (boolean field)
- [ ] Add column "Synonym Full Name" (?)

Hybrids: 
- [ ] Add column "Hybrid" (boolean field)
- [ ] Add column "Parent 1 Full Name" 
- [ ] Add column "Parent 2 Full Name"

**Comment by FedorSteeman** [comment]
In #448 @jlegind reported the appearance of hybrids in the app export file and asks for a solution on how to handle these: 

> ## What is the issue ?
> 
> We have no way of handling hybrid names in the app. They are commented in the remarks field. Relates to #28
> ### Detailed description of the issue.
> 
> The names "x cotula" and "x tinctoria" appeared in an export and were noted in the remarks field, for the species Anthemis arvensis. See attached file : [NHMD_Herba_20231019_16_26_SS.csv](https://github.com/NHMDenmark/Mass-Digitizer/files/13249686/NHMD_Herba_20231019_16_26_SS.csv)
> ### Estimate level of effort required.
> 
> unknown
> ### What is the expected acceptable result.
> 
> A situation where the hybrids would be available in the app taxonomy for auto suggest.

Specify can already handle hybrids. What #28 specifies is how the app db should be adapted to record these so they can readily imported using Workbench. Since this has not happened, we cannot at the moment import hybrids, though I remember we discussed that we could import these as-is to be fixed after import. Otherwise, it would be better to park these cases. Alternatively, we could adapt the PostProc script to add the necessary columns for import. However, I don't think that's possible, since it needs to be fed the two parent taxa.

@PipBrewer What do you recall and what would you prefer?

**Comment by PipBrewer** [comment]
Slack discussion sparked by https://github.com/NHMDenmark/Mass-Digitizer/issues/448

Pip Brewer
K, so I now I see it.  Anthemis arvensis x cotula is presumably what the digitisers see on the folder.
[2:23](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699017829793689)
So, in this case until we develop hybrid capacity in the app, "arvensis x cotula" could actually go in the name field in Specify and mark as hybrid box is checked? How much would that mess up Specify? (edited) 
[2:26](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699017975176819)
How SHOULD it work? We add parent1 as Anthemis arvensis", parent 2 as Anthemis cotula. What happens then? What does the name field look like?


Fedor Alexander Steeman
  [2:26 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699017993281809)
Actually, it would not mess up Specify other than linking a misleading taxon to the specimen. But since the information is added to the remarks field, in theory we could fix after import.
[2:27](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018024332699)
BTW I added my mail comments to ticket #448 now plus some more.


Pip Brewer
  [2:27 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018050584839)
Shall I start adding comments to a 4th ticket?
[2:27](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018056833169)
Sorry, just joking


Fedor Alexander Steeman
  [2:27 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018068456229)
Should we keep the discussion in ticket #28 ?


Pip Brewer
  [2:27 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018075352059)
:shrug:
[2:28](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018080065669)
It's getting confusing


Fedor Alexander Steeman
  [2:28 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018092316349)
Not sure what extra information the new tickets adds.
[2:28](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018112670019)
Or why a whole new ticket was needed for the same issue.


Pip Brewer
  [2:29 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018177999009)
How SHOULD it work? We add parent1 as Anthemis arvensis", parent 2 as Anthemis cotula. What happens then? What does the name field look like?


Fedor Alexander Steeman
  [2:30 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018228295119)
Yes, I was gearing up to answer that... One moment...


Pip Brewer
  [2:30 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018239431419)
I'll go make a cuppa...


Fedor Alexander Steeman
  [2:32 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018332755269)
I haven't tried this in Workbench, but in theory adding the columns (to the import file) as specified in #28 should enable import of hybrids.


Pip Brewer
  [2:33 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018392156899)
I'm just wondering what goes in the name field. Because we could just duplicate the look of that and then add the parent taxa as well. The digitisers would just search in the app on the name string?
[2:35](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018554728969)
Don't worry, I've just searched and found a couple of examples in Specify


Fedor Alexander Steeman
  [2:37 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018637091059)
Yeah, I suppose we'd need a special popup in the app for specifying hybrids, so both parent taxa can be sought and added.


Pip Brewer
  [2:42 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699018942993069)
In the meantime, it looks like my proposed workaround has already been used a couple of times previously in vascular plants. I think we should create a ticket for a tick box for hybrid, which then brings up a pop up box. In the meantime, the digitisers type it in as it appears on the fron of the folder, e.g., "Anthemis arvensis x cotula" and we sort it out in post-processing. We can build up the example cases as we encounter them. In this case, Anthemis is the parent taxon, "arvensis x cotula" goes in species, hybrid box is ticked, and we can add parent taxa in here as well. Is that too much? Thoughts? 
[@Bhupjit Singh](https://nhmddigicoll.slack.com/team/U05AG8J7WJF)
 
[@Fedor Alexander Steeman](https://nhmddigicoll.slack.com/team/U02NQKG1BFV)
 
[@Jan Kristoffer Legind](https://nhmddigicoll.slack.com/team/U039GDCRX4N)


Fedor Alexander Steeman
  [2:44 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019067459409)
What about cross-generic hybrids?


Pip Brewer
  [2:45 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019138995129)
Like I said, we build up cases as we encounter them. Sometimes, the hybrid has its own name, other times it doesn't. Sometimes one of the hybrids is a variant or subspecies. The possibilities are endless. If it is across genera, the digitisers would still type it in as it appears e.g., "Pippus populus x Fedoris nhmdensis"
[2:46](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019198088829)
The parent taxon here would need to be identified. I'm not sure the digitisers would ever be able to provide that answer.
[2:47](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019262693419)
In that case, I would stop the post-processing, put a ticket in and get the relevant curator to provide the answer. Then finish processing. Or we could just look up on the taxon tree for the parent. (edited) 


Fedor Alexander Steeman
  [2:49 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019357044019)
To my understanding of how hybrids are recorded in Specify, with "parent taxon" I here mean the two parent taxa of the hybrid, in this case being "Anthemis arvensis" and "Anthemis cotula". (edited) 


Pip Brewer
  [2:50 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019441729349)
We are on the same page, I think. There are 2 fields for hybrid for parent taxon. There is then the overarching parent. I think we are supposed to fill all three in? (edited) 


Fedor Alexander Steeman
  [2:51 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019492113809)
Forgetting about cross-generic hybrids, I'd say yes to the need for a tick box, no to the need for a popup and an OK to writing the hybrid taxon name as is on the label i.e. "Anthemis arvensis x cotula" and this could be sorted in PostProc
[2:51](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019506843069)
I don't see what the popup would serve


Pip Brewer
  [2:52 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019551161979)
The pop up would enable us to populate the columns for parent hybrid 1 and parent hybrid 2, so there is no confusion in post-prcoessing?


Fedor Alexander Steeman
  [2:53 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019586502669)
Oh OK. Double insurance then.


Pip Brewer
  [2:53 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019617143139)
:shrug: maybe? It would reduce the need for post-processing which is what we ultimately want?


Fedor Alexander Steeman
  [2:53 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019624982479)
I think the popup would just fill in the hybrid name for the digitizer (edited) 
[2:54](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019652168469)
And the parent taxa are saved in their respective columns
[2:55](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019717494319)
Alternatively, and more risky, the digitizer would mark the taxon as hybrid, start typing the full smear, and then that is interpreted by the app as two distinct parent taxa by splitting on the " x "
[2:55](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019754658099)
Or perhaps the presence of the " x " would automatically mark it as hybrid.


Pip Brewer
  [2:56 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019762783609)
They would need to type full binomial/trimonial in for each for that to be more foolproof, but that could work.
[2:56](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019780045969)
E.g., Anthemis arvensis x Anthemis cotula


Fedor Alexander Steeman
  [2:56 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019790469369)
"Med livrem og seler" as they say in Danish


Pip Brewer
  [2:57 PM](https://nhmddigicoll.slack.com/archives/C043U5CD9S5/p1699019832879139)
Belts and braces is the equivalent phrase in English I guess
:+1:
1

**Comment by PipBrewer** [comment]
@FedorSteeman to test if hybrids can be imported into Specify using workbench

**Comment by FedorSteeman** [comment]
I've tried mapping in Workbench, but couldn't find a way. I then went investigating and it turns out that it's apparently not possible to fully map hybrid species in Workbench: https://discourse.specifysoftware.org/t/workbench-map-hybrid-species-how/1261/6 

It is however possible to map the "IsHybrid" flag so the proposal should instead be just writing the hybrid name pattern in the species name field as well as adding a "hybrid species" tickbox. The code for deriving taxon tank will also have to be changed accordingly.

**Comment by PipBrewer** [comment]
Meeting with @jlegind and @FedorSteeman just now. The following is agreed. Until the app can be updated to represent hybrids we will do the follow:
In Open Refine, manually check for hybrids. Check the correct things are in the name and parent name columns and add a column for "Is hybrid" with a 

- For the fictional hybrid, "Janus pippus x fedoris", "pippus x fedoris" goes in name and "Janus" goes in Parent name. The rank is species.
- For the fictional hybrid "Janus pippus x Chelsea fedoris", "pippus x Chelsea fedoris" goes in name and "Janus" goes in Parent name. The rank is species.
- For the fictional hybrid "Janus pippus nhmdensis x Janus chelseai floortwoensis", "nhmdensis x Janus chelseai floortwoensis" goes in name and ""Janus pippus" goes in Parent name. The rank is subspecies.
- Etc

The digitisers simply write whatever is on the folder in the taxon name box in the App.

**Comment by RebekkaML** [comment]
An additional thing that might be a problem here is that some Hybrids also get their own new name instead of the parent names, so in this case they would need to be looked up manually. 
Example: The loganberry (Rubus × loganobaccus) is a hybrid of the North American blackberry (Rubus ursinus) and the European raspberry (Rubus idaeus). 
So it is still marked as a hybrid with an x, but the species name is a new one.

**Comment by PipBrewer** [comment]
@RebekkaML I think this is fine. Rubus is in the parent taxon and "x loganobaccus" goes in the name. As part of the digitisation process we don't know the hybrid parent taxa - they can be added later by collection managers or curators as needed.

**Comment by FedorSteeman** [comment]
@PipBrewer  This may not be something to be fixed in the app, since we cannot import hybrids and synonyms as such into Specify. We can only fix these after import manually (or perhaps with some clever SQL).

**Comment by FedorSteeman** [comment]
Actually, on closer thought hybrids have been taken care of in ticket #346 and this case can now be closed.
