### ISSUE TITLE
[ISSUE] Repeated taxon numbers

### ISSUE THREAD

**Issue by bhsi-snm** [NHMDenmark/Mass-Digitizer#407]
# Template for isues/tickets in DigiApp
##  What is the issue ?

```
There is an issue with the NHMA taxonomy and taxonnumbers – there are repeated taxon
numbers, which should not happen (e.g., number 16 appears twice in the database). 
This is a huge issue and I don't fully understand it myself, needs discussion
```

## Why is it needed/relevant ?
```
# Explain the need, relevance.
# Give scenario(s) of why and when this could be relevant. 

```
## Estimate level of effort required.

```
# easy
# difficult
# hard

```

## What is the expected acceptable result.

```
#  How to approach it?
#  Give a clear approach/potential solution on how to resolve it.
#  What steps would be required to do this ?
#  It might also be an idea to put some pseudocode if relevant.

```

# What could be the challenges ? 

```
Is there a potential risk to this. 
Could it affect another part of the project. 
```

# What test are required ?

`New tests/Could include reference to the existing test`

# What documentation required?

`Could refer to existing documentation and changes in relevant doc files.`

# Remarks

**Comment by FedorSteeman** [comment]
In the case of taxon number 16, these seems to be synonyms: https://www.gbif.org/species/9578719

**Comment by FedorSteeman** [comment]
Synonyms do not in themselves constitute an actual issue, since these would be sorted in Specify or in any case GBIF, and both accepted names and synonyms should be available. However, if the app consistently chooses the synonym to populate the taxon fields instead of the accepted name, that would need to be mitigated somehow.

**Comment by FedorSteeman** [comment]
After conferring with @bhsi-snm and then @PipBrewer the easiest solution is going back to the question why the taxon numbers are repeated in the first place. This seems like a mismatch during import.

**Comment by FedorSteeman** [comment]
Reduced the number of re-used taxon numbers to 130, but there are still some cases where a single taxon number actually was assigned to multiple taxa: 

![image](https://github.com/NHMDenmark/Mass-Digitizer/assets/10909008/923080cd-58bf-4773-8635-869004985657)

Solution could be to integrate the secondary (serial?) number into the taxon number and advise digitizers to be mindful of and use that one. However, it's unclear whether this would work in practice.

**Comment by FedorSteeman** [comment]
Note: Fix is invalid, because some of the species were assigned to new genera so the full names don't match. I will need to redo this

**Comment by FedorSteeman** [comment]
Note: After close investigation the previous was actually correct in removing the taxon number from certain species (like _Acalypta gracilis_) and that was not because the species were assigned to new genera, but rather because the file I was supplied with processed taxon-sortnr pairs had incorrectly assigned these taxon numbers to those species in question. 

However, a different problem was discovered where there was a limited number of cases where the genus name was not added to the full name, which lead to the SQL script (MassDigitizer/sql/specify/UpdateSetTaxonNumber.sql) failing to add those taxon numbers to the taxa in question, since it relied on full name (binomial). The latter file is now fixed by having redone the binomial full name in those cases. 

Then the script MassDigitizer/sql/ExtractTaxonNames.sql could be run again resulting in a now correct MassDigitizer/sql/editions/NHMA/entomology/Species-Batch1.sql
