### ISSUE TITLE
Update to GREL script - collection name

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#411]
### Issue
The postprocessing step did not correctly update the collection name derived from the storage location.

The collection manager decides the collection name and we have to follow suit.

### Risk
The risk bound to this issue is that we must have conformity in the record data or else queries parameters become uncertain since the property searched on might have multiple values.

### Solution
Update the GREL script with the step needed for the right collection string for NHMD Vascular Plants which is now:
 "C-Danish Herbarium"

The Script lives here: https://github.com/NHMDenmark/Mass-Digitizer/blob/main/OpenRefine/post_processing.json

**Comment by FedorSteeman** [comment]
This is not necessary, since with each release of the app the predefined data is regenerated on the basis of the current status of storage node names in Specify using  https://github.com/NHMDenmark/Mass-Digitizer/blob/main/MassDigitizer/sql/specify/ExtractStorageLocations.sql 

Adaptation of the script to the new situation will be covered by #398
