### ISSUE TITLE
Shift tab from Taxon name field crashes app

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#412]
## Issue
Under NHMA sign in, the app will crash if the user shift-tabs out of the Taxonomic ID field.
### Acceptable solution
Tabbing behavior should be fluid and not throw off artifacts.

**Comment by FedorSteeman** [comment]
The tabbing and shift-tabbing need to be reworked.

**Comment by FedorSteeman** [comment]
Shift-tabbing with activated taxon number field caused the app to go in an infinite loop constantly switching between setting focus on taxon number field and barcode field. The cause of this bug could not be traced, but the infinite loop is now stopped in its tracks by measuring the amount of time elapsed and breaking when it is shorter that 50 ms.

Another major change that was made with the idea to prevent UI triggers that would the possible cause is getting the form values from events instead of directly from the window. It may need to be tested, however, if all values are still correctly persisted.

**Comment by jlegind** [comment]
`elif event == 'inpTaxonName':         `       
             `    # Ensure any tabs are kept from creeping into the taxon name entered`
                `    if "\t" in keyStrokes:`
                    `        self.setFieldFocus('inpCatalogNumber')`

**Comment by jlegind** [comment]
Shift tab in the App for NHMA taxon ID field sends the focus to Barcode.
