### ISSUE TITLE
When stepping back Record ID is not cleared on save

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#422]
##  What is the issue ?
After stepping back to a previous record and updating - saving the changes does not clear the record ID (lower left corner) 

### Detailed description of the issue. 
After creating a new record we expect some fields to persist (sticky fields) and some to be cleared. One of these is the 'record ID' (key == txtRecordID).

### Why is it needed/relevant ?
We rely on the record ID to identify whether we are operating on an existing record or if we are creating an entirely new record.

### Estimate level of effort required.
Easy

### What is the expected acceptable result.
When stepping back to a previous record and updating, a save should bring the App back to the latest record with the record ID cleared.

**Comment by FedorSteeman** [comment]
When saving any existing record, the record ID should *not* be cleared, because the requirement for a while now has been that you stay on the record. See e.g. #315  

Only in the follwing cases should the record ID be cleared or empty: 
- When you start the app 
- When you save a _new_ record 
- When you move forwards beyond the last record

@PipBrewer Please confirm that this is still the requirement.
