### ISSUE TITLE
Update to GREL script to incorporate other columns in Remarks table in Specify

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#444]
When adding data from Notes field in the App to the Remarks field in Specify, need to also fill in data into the other two columns in the Remarks table (these are "Source" and "Date"). In the source column we should add "DaSSCo digitisation" and in the date column, the date the data was added to the app. The data for these two columns therefore needs to be incorporated into the GREL script. Theoretically, we should make it so that multiple rows in the remarks field is possible.

**Comment by FedorSteeman** [comment]
Yes, I had a talk with @AstridBVW about how notes are currently lumped into the base specimen "Remarks" field, circumventing the "tabular" Remarks records related to the specimen. I had specifically designed for DaSSCo purposes following @PipBrewer 's specifications, but these have until now not been put to use. There should be a clear way to funnel data into these fields, otherwise the GREL script won't know how to tease out this information. Perhaps even we should make additions to the UI for a controlled entry of this information.

**Comment by FedorSteeman** [comment]
No need to adapt the UI. The GREL script can do the trick.

**Comment by jlegind** [comment]
Adding these columns to new exports is now part of the post processing.
