### ISSUE TITLE
Solitary "One specimen on multiple objects" value in Digi app export

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#446]
## What is the issue ?
The multi-specimen/object record usually come in pairs or larger groups. A single record with the MOS type name is suspicious. 

### Detailed description of the issue. 
During post processing I discovered this 'anomaly' and alerted the project lead. 
### Why is it needed/relevant ?
This issues reduces the data quality.
### Explain the need, relevance.
It begs the question: Which other records belong to this group?

### Estimate level of effort required.
 easy

### What could be the challenges ? 
Going back to the collection and finding the specimen
### Remarks
I went ahead and imported the file NHMD_Herba_20231013_15_59_RL.csv anyway.
Csv attached.
[NHMD_Herba_20231013_15_59_RL.csv](https://github.com/NHMDenmark/Mass-Digitizer/files/13241014/NHMD_Herba_20231013_15_59_RL.csv)

**Comment by AstridBVW** [comment]
1. 935359: I found the image for NHMD 935359, and it has “1/2” in the upper right corner. There is another image in the same folder, NHMD 935360, which does not have a label but “2/2” in the upper right corner and some information written on the sheet matching with the label on NHMD 935359. Thus, NHMD 935359 is a MOS with NHMD 935360. The exported data had already been imported so they needed to be connected in Specify. However, when I went to do that, there was no record for NHMD 935360 in Specify. The problem was that the sheet had been barcoded and imaged but NOT scanned into the digi app. This was not known when the dummy records were deleted in Specify before importing so the record NHMD 935360 was deleted and then not recreated during the import. I recreated it myself based on NHMD 935359 and assigned it NHMD number 935360. They are now connected through the container.

2. 935037: I have checked the image, and both NHMD numbers have the same image (NHMD 935037 and 934972). The exported data was already imported so I have connected them through the container in Specify.

3. “ov” is short for “obstructed view”. This term was used in the beginning before we had controlled vocabulary for obscured view of specimen and/or label. This has already been imported to Specify, @PipBrewer let me know if you want it removed or changed.
