### ISSUE TITLE
New taxon flag in Specify

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#455]
At the moment, the New Taxon flag in the taxon records in Specify uses a different field for different collections/institutions. It would be helpful if we were consistent.

Right now, to facilitate digitisation, we need this field to be visible (searchable and so collection managers and curators can deselect after taxon has been checked) for NHMD Vascular Plants, NHMD Entomology and NHMA Entomology.

For NHMD entomology, the GREL script is currently being mapped to extinct taxon flag.

**Comment by FedorSteeman** [comment]
We mapped the "New taxon flag" to the taxon.YesNo1 field in Specify and re-captioned it as such. However, it turned out that the original purpose of the field was to indicate whether a taxon is extinct and a limited amount of taxa across all NHMD collections seem to have ticked this off. There are 546 in total and are the following: [SpTaxaMarkedExtinct.csv](https://github.com/NHMDenmark/Mass-Digitizer/files/13363175/SpTaxaMarkedExtinct.csv)

The following disciplines are affected: 
- Entomology
- Vertebrate Paleontology
- Danekrae 

There are 2 possible solutions for this: 
- [ ] With relevant staff's permission repurpose the "extinct" flag as "new taxon" 
- [ ] Choose another field and edit the taxon form to show that alongside the "extinct" flag 

The problem is that it's unclear how the taxon form can be changed, if at all. If not, then we we're forced to use solution 1. 

The specimens for Entomology were rove beetles included in amber. Sree was OK with me repurposing it, but recommends I asked Alexey first. I will ask Bent Lindow and Laura Pavesi about their respective discplines.

**Comment by FedorSteeman** [comment]
Discussions with some staff revealed that they'd prefer the field be retained for its intended purpose, which is a better idea anyway for standardization issues. It was revealed on Discourse that it's possible to edit the taxon form also. So it's best we repurpose another field (YesNo2) for the "New Taxon" flag and add that to the taxon form.

**Comment by FedorSteeman** [comment]
Got it to work in test: 
![image](https://github.com/NHMDenmark/Mass-Digitizer/assets/10909008/c7f7d2c8-ebe4-4ca4-9411-f6a7c7ad2f55)

Next steps are: 
- [ ] Implement in live db for NHMD Entomology, NHMD Botany and NHMA Entomology
- [ ] Change captions of field in Specify schema config and inform DaSSCo team (@jlegind) to redo the mapping 
- [ ] Fix this flag from earlier DaSSCo imports to be move from one field (YesNo1) to the other (YesNo2)

**Comment by FedorSteeman** [comment]
Relevant DanSpecify commit: https://github.com/NHMDenmark/DanSpecify/commit/dce91bc05eba14a5b9379c7b755e3af76096b368

**Comment by FedorSteeman** [comment]
No earlier imports needed to be fixed. Problem solved.
