### ISSUE TITLE
Taxon "Galinsoga ciliata subsp. subsp." in Specify

### ISSUE THREAD

**Issue by RebekkaML** [NHMDenmark/Mass-Digitizer#496]
The Taxon "Galinsoga ciliata subsp. hispida" mistakenly appears as "Galinsoga ciliata subsp. subsp." in the Vascular plants collection in Specify. It seems like an error that occurred during importing. It should be easy to fix, but we need to make sure it doesn't happen regularly.

**Comment by PipBrewer** [comment]
I would recommend checking the exported app file and the post-GREL script one for these records. This is to see what happened and if there is a bug.
Check that all associated specimen records are DaSSCo and what the correct taxon is for them. If they are all the same, we can change the taxon record in Specify.

**Comment by AstridBVW** [comment]
This ticket is related to #511

**Comment by AstridBVW** [comment]
I checked the files. The error occurred because "subsp." was added to the taxonfullname in the corrected (checked) version of the file (don't know why). In post-processing the actual subspecies name was lost and "subsp." was set as the subspecies name instead. In Specify, "subsp." is added as a prefix before the subspecies name in the taxonfullname, thus it ended up being "subsp. subsp.". All the associated records were DaSSCo records so I have corrected the taxon record.
