### ISSUE TITLE
Develop script to transfer AU data to Specify

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#516]
Arhus University Herbarium currently have data that is equivalent to NHMD's digi app exports (with some differences). This needs a GREL script writing to transform it so it can be imported into Specify

**Comment by beckerah** [comment]
We've now decided to put together a Python script for this instead of creating a new GREL script for OpenRefine. We just got our first data dump from AU yesterday. The next step will be to go through the data and decide which fields need to be imported into Specify.

**Comment by beckerah** [comment]
Steps for script will be:
Steps will be:

1.     Loop through any csv file in a folder that ends in _checked or _checked_corrected
2.     Store the filename as a variable
3.     Modify filename to end in _processed.tsv
4.     Add in appropriate columns, some adding values for all rows, others adding values based on values in other columns (see GREL steps)
5.     Rename columns
6.     Reorder columns
7.     Spit out tsv with correct name
8.     Add filename to log
9.     Move processed tsv to correct Ready for Specify folder
10.     Move original csv to correct Archive

**Comment by beckerah** [comment]
The following data needs to be pulled from the species-web db:

**From table Specimen:**

- id 
- barcode
- guid
- digitiser
- date_asset_taken (catalogued date)
- folder id (to match with Folder Versions table)

**From table Folder Versions:**
- id (to match with Specimen table)
- folder id
- area (broad geographic region)
- family
- genus
- species
- variety
- subspecies
- highest classification (actually lowest classification)

I've written a SQL query to pull this data and join it (currently a left join where folder versions is left). I need to add barcodes to this when we update the db.

**Comment by beckerah** [comment]
Additional information that needs to be added:

projectnumber: DaSSCo
publish: True
storedunder: True
preptypename: Sheet
count: 1
collection: ???
datafile_remark: [name of db export]? Possibly by date? Is this useful?
datafile_source: DaSSCo data file
datafile_date: [date of digitization]

At this point, there doesn't seem to be a need for fields like qualifier/addendum or remarks.
What is the collection?
Will there be hybrids?
Do we need flags for new taxonomy or would that be redundant since Birgitte is already checking everything in species-web?

**Comment by beckerah** [comment]
After some additional data exploration, it looks like the fields: family, genus, species, etc do not always reflect the correct taxonomy. Therefore, it is safer to pull the taxonomy from the gbif_match_json field instead. From this field, relevant info we can pull: 

- taxonID (Do we want to retain taxonID (example: "gbif:2970468), or separate taxon source ("gbif") and id ("2970468")?)
- kingdom (needed?)
- phylum (needed?)
- order (needed?)
- family
- genus
- species
- variety
- subspecies
- scientificName (the full name, including author)
- canonicalName (the full name, excluding author)
- authorship (just the author by itself)

**Comment by beckerah** [comment]
I've got the script creating all the relevant info but I still have some questions that I need to answer:

@PipBrewer do you know the answer to any of these? And is Birgitte the person I should talk to about anything in this list that we're not sure about?

❓ Questions:
- At this point, there doesn't seem to be a need for fields like qualifier/addendum or remarks. (Accurate statement?)
- What is the collection? (AU Herbarium?)
- Will there be hybrids? (These would need to be handled slightly differently because gbif does not keep hybrids in their backbone, therefore the gbif_match_json will always be null for them.)
- Do we need flags for new taxonomy or would that be redundant since Birgitte is already checking everything in species-web?
- The digitiser always shows as Birgitte right now. But should it always be Charlotte instead?
- Do we want to keep a taxon key? If so, which field do we want for the key? There are two options, like in the following example: "key": 5347053 or "taxonID": "gbif:5347053"
- How do we want to reference the taxon key source? GBIF? GBIF.org?

**Comment by beckerah** [comment]
After chatting with Pip, I have some answers, more questions:

> At this point, there doesn't seem to be a need for fields like qualifier/addendum or remarks. (Accurate statement?)

We might want some things from the gbif record to go in remarks, but likely not. But there's a new question: How are we going to handle synonyms? I need to play around with Specify and see if there's a useful way to document these.

> What is the collection? (AU Herbarium?)

I need to ask Fedor if he's discussed with AU whether or not they want to divide up their collections so we can figure out if the collection is even needed. I assume it would be best to include it, in which case: is it easy to update AU Herbarium to something else in the future if needed?

> Will there be hybrids? (These would need to be handled slightly differently because gbif does not keep hybrids in their backbone, therefore the gbif_match_json will always be null for them.)

This is a question for Birgitte. A second related question is: how is she handling any taxa that does not pull a successful match from gbif? And a question for me: is Aksel's code pulling the gbif match from the backbone? (My assumption is yes?)

>  Do we need flags for new taxonomy or would that be redundant since Birgitte is already checking everything in species-web?

This would be redundant EXCEPT in cases like the above, where there is no match in gbif. In that case, maybe we need a check taxon flag if the gbif_match_json is null? But are these even being approved at all in species-web? 

> The digitiser always shows as Birgitte right now. But should it always be Charlotte instead?

Because this becomes the cataloger in Specify, right now it will always be Birgitte. Can update all records to her name. (Maybe add: if empty, add Birgitte)

> Do we want to keep a taxon key? If so, which field do we want for the key? There are two options, like in the following example: "key": 5347053 or "taxonID": "gbif:5347053"
> How do we want to reference the taxon key source? GBIF? GBIF.org?

I need to ask Fedor & Isabel if there is a standardized way of citing gbif taxon records. Pip found this as an example citation: _GBIF Secretariat: GBIF Backbone Taxonomy. https://doi.org/10.15468/39omei Accessed via https://www.gbif.org/species/5284517 [13 January 2020]_ but I'm not sure if that's useful for current Specify fields taxon key & taxon key source.

**Comment by beckerah** [comment]
How to handle synonyms: I talked to Fedor about this, and he showed me how to synonymize taxa in the Specify taxon tree manually. He also mentioned that he is currently working on a tool that can do this via import. To make use of this tool, I will need the script to create a CSV file with the taxa that need to be synonymized. The github repo for a similar tool, showing the format I will need this CSV in, is here: https://github.com/melton-jason/Specify7-Api-Demo

For the collection name: Birgitte says that they don't have their herbarium divided into any sub-collections, it's just all “Aarhus University Herbarium”. It might be easiest to just add this as the site/building and not include a collection name for the records. I'll double-check with Fedor.

There will be hybrids, but Birgitte says she thinks species-web can handle those. I'll just build into the script a search for " x " in scientificName to check the 'is hybrid' box in Specify. I don't see any other way to identify hybrids.

Birgitte says that she has not run into any instances where she was unable to find and select the correct taxon name if no gbif match was returned. She said originally they were having trouble with homonyms but Aksel fixed that.

**Comment by beckerah** [comment]
- [ ] Add Birgitte's name to digitiser field when its empty
- [ ] Discuss with Fedor about updating storage tree to include Institution: Aarhus University, site/building: Aarhus University Herbarium
- [ ] If scientificName field contains " x ", add isHybrid: True. (Also need to make sure it is correctly retaining full names)
- [ ] Pull key from json to enter into taxon key, add 'GBIF' to taxon key source for all

**Comment by beckerah** [comment]
One final thing to check: when pulling data from the species-web db, should I only be including rows with approved_at or approved_by in the sql query?

**Comment by beckerah** [comment]
It looks like we can identify the correct row via the created_at column:

![image](https://github.com/user-attachments/assets/a115a605-82f6-4411-99dd-defbfb885bab)

I'll amend the SQL query that pulls the data to reflect this.

**Comment by beckerah** [comment]
The synonym CSV needs to have duplicates dropped every time. Should just be a quick fix in the script.

**Comment by beckerah** [comment]
The script is finished, has been tested, and is working as expected. I'll close this ticket and open new ones for establishing the data workflow and updating documentation.
